# SECTION 1: PRODUCTS END POINT

In [37]:
import requests

In [38]:
products_url = "https://dummyjson.com/products"

In [39]:
products_data = requests.get(products_url)

In [7]:
#check response

In [40]:
products_data.status_code

200

In [10]:
#Extract the JSON response

In [41]:
products_json = products_data.json()

In [13]:
#check data type

print(type(products_json))

In [14]:
#check how many products

In [22]:
#Convert to DataFrame

In [42]:
import pandas

In [53]:
df = pandas.DataFrame(products_json['products'])

In [67]:
#check the first 3 columns

In [68]:
df.head(3)

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [35]:
#Save as CSV

In [57]:
df.to_csv("products_data.csv", index=False)

In [58]:
#verify the csv was saved

In [61]:
import pandas
check = pandas.read_csv("products_data.csv")
print(f"✅ File saved successfully!")
print(f"Shape: {check.shape}")
check.head()

✅ File saved successfully!
Shape: (30, 22)

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"['beauty', 'mascara']",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/bea...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"['beauty', 'eyeshadow']",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/bea...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"['beauty', 'face powder']",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/bea...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"['beauty', 'lipstick']",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/bea...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"['beauty', 'nail polish']",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/bea...,https://cdn.dummyjson.com/product-images/beaut...

In [62]:
# SECTION 1: CARTS END POINT

In [63]:
carts_url = "https://dummyjson.com/carts"

In [65]:
carts_data = requests.get(carts_url)

In [70]:
# Check response

In [71]:
carts_data.status_code

200

In [72]:
# Extract JSON

In [84]:
carts_json = carts_data.json()

In [85]:
#Convert to DataFrame

In [86]:
import pandas

In [87]:
df = pandas.DataFrame(carts_data)

In [89]:
df.head(3)

                                                   0
0  b'{"carts":[{"id":1,"products":[{"id":162,"tit...
1  b'3,"discountedTotal":105.41,"thumbnail":"http...
2  b'le":"Generic Motorcycle","price":3999.99,"qu...

In [90]:
#save output in csv file

In [92]:
df.to_csv("carts_data.csv", index=False)