In [ ]:
#

In [15]:
#Import requests

In [31]:
import requests

In [32]:
url = "https://raw.githubusercontent.com/muriithilydia46-wq/Hospital_data/refs/heads/main/HOSPITAL_DATA.json"

In [33]:
hospital_url = requests.get(url)

In [34]:
hospital_url.status_code

200

In [37]:
mock_data = hospital_url.json()

print (type(mock_data))

<class 'list'>

In [38]:
mock_data [:2]

[{'hospital_name': 'IOWA SPECIALTY HOSPITAL- CLARION',
  'nato_phonetic': 'India Romeo Lima Mike Zulu Golf Victor Sierra Hotel Quebec Kilo Delta',
  'gender': 'Female',
  'street_address': '64301 Evergreen Pass',
  'city': 'Krajan Jabungcandi'},
 {'hospital_name': 'SCOTT & WHITE HOSPITAL',
  'nato_phonetic': 'Uniform Alfa Lima November Golf Romeo Bravo Victor Hotel Tango Whiskey',
  'gender': 'Male',
  'street_address': '2 Hansons Lane',
  'city': 'Além Paraíba'}]

In [40]:
##Pandas

In [41]:
import pandas

In [42]:
df = pandas.DataFrame(mock_data)

In [43]:
df

,hospital_name,nato_phonetic,gender,street_address,city
0,IOWA SPECIALTY HOSPITAL- CLARION,India Romeo Lima Mike Zulu Golf Victor Sierra ...,Female,64301 Evergreen Pass,Krajan Jabungcandi
1,SCOTT & WHITE HOSPITAL,Uniform Alfa Lima November Golf Romeo Bravo Vi...,Male,2 Hansons Lane,Além Paraíba
2,SHARKEY ISSAQUENA COMMUNITY HOSPITAL,Sierra Quebec Romeo Kilo Papa Lima Zulu Alfa Y...,Male,74381 Vernon Parkway,Maslovare
3,COLUMBIA ST. MARY'S HOSPITAL MILWAUKEE INC,Juliett Yankee Tango Golf Quebec Bravo Delta U...,Female,23 Lakewood Park,Qumudi
4,"ANGEL MEDICAL CENTER, INC.",Sierra X-ray Romeo Victor Alfa Bravo November ...,Male,31725 Carberry Hill,Tamisan
...,...,...,...,...,...
995,BROOKS COUNTY HOSPITAL,Papa Hotel Alfa X-ray Bravo Sierra Yankee Foxt...,Agender,98 Coleman Street,Mawlamyinegyunn
996,NEW YORK CITY HEALTH AND HOSPITALS CORPORATION,Alfa Kilo Tango Quebec Romeo Delta X-ray Zulu ...,Male,505 Delaware Junction,Moncada
997,VARIETY CHILDREN'S HOSPITAL,X-ray Delta Yankee Zulu November Foxtrot Sierr...,Male,222 Aberg Point,Veracruz
998,LIFELINE MEDICAL CENTER,Tango Yankee Alfa Juliett Lima Romeo India Bra...,Male,12 Lakewood Gardens Road,Češinovo
999,DLP CONEMAUGH MEMORIAL MEDICAL CENTER LLC,Lima Zulu Quebec Echo Delta Juliett Uniform Ro...,Female,14 Rigney Avenue,Duitama

In [44]:
df.head(5)

,hospital_name,nato_phonetic,gender,street_address,city
0,IOWA SPECIALTY HOSPITAL- CLARION,India Romeo Lima Mike Zulu Golf Victor Sierra ...,Female,64301 Evergreen Pass,Krajan Jabungcandi
1,SCOTT & WHITE HOSPITAL,Uniform Alfa Lima November Golf Romeo Bravo Vi...,Male,2 Hansons Lane,Além Paraíba
2,SHARKEY ISSAQUENA COMMUNITY HOSPITAL,Sierra Quebec Romeo Kilo Papa Lima Zulu Alfa Y...,Male,74381 Vernon Parkway,Maslovare
3,COLUMBIA ST. MARY'S HOSPITAL MILWAUKEE INC,Juliett Yankee Tango Golf Quebec Bravo Delta U...,Female,23 Lakewood Park,Qumudi
4,"ANGEL MEDICAL CENTER, INC.",Sierra X-ray Romeo Victor Alfa Bravo November ...,Male,31725 Carberry Hill,Tamisan

In [45]:
#reference column name

In [48]:
df["hospital_name"]

0                    IOWA SPECIALTY HOSPITAL- CLARION
1                              SCOTT & WHITE HOSPITAL
2                SHARKEY ISSAQUENA COMMUNITY HOSPITAL
3          COLUMBIA ST. MARY'S HOSPITAL MILWAUKEE INC
4                          ANGEL MEDICAL CENTER, INC.
                            ...
995                            BROOKS COUNTY HOSPITAL
996    NEW YORK CITY HEALTH AND HOSPITALS CORPORATION
997                       VARIETY CHILDREN'S HOSPITAL
998                           LIFELINE MEDICAL CENTER
999         DLP CONEMAUGH MEMORIAL MEDICAL CENTER LLC
Name: hospital_name, Length: 1000, dtype: object

In [51]:
df = df.to_csv("mock_data.csv")

In [52]:
import pandas as pd

df = pd.read_csv("mock_hospital_data.csv")

print(f"Shape: {df.shape}")
print(f"\nColumns: {list(df.columns)}")
print("\nFirst 5 rows:")
df.head()

Shape: (1000, 6)

Columns: ['Unnamed: 0', 'hospital_name', 'nato_phonetic', 'gender', 'street_address', 'city']

First 5 rows:

,Unnamed: 0,hospital_name,nato_phonetic,gender,street_address,city
0,0,IOWA SPECIALTY HOSPITAL- CLARION,India Romeo Lima Mike Zulu Golf Victor Sierra ...,Female,64301 Evergreen Pass,Krajan Jabungcandi
1,1,SCOTT & WHITE HOSPITAL,Uniform Alfa Lima November Golf Romeo Bravo Vi...,Male,2 Hansons Lane,Além Paraíba
2,2,SHARKEY ISSAQUENA COMMUNITY HOSPITAL,Sierra Quebec Romeo Kilo Papa Lima Zulu Alfa Y...,Male,74381 Vernon Parkway,Maslovare
3,3,COLUMBIA ST. MARY'S HOSPITAL MILWAUKEE INC,Juliett Yankee Tango Golf Quebec Bravo Delta U...,Female,23 Lakewood Park,Qumudi
4,4,"ANGEL MEDICAL CENTER, INC.",Sierra X-ray Romeo Victor Alfa Bravo November ...,Male,31725 Carberry Hill,Tamisan

In [53]:
# Drop the unnecessary index column
df = df.drop(columns=['Unnamed: 0'])

df.head()

(1000, 5)

,hospital_name,nato_phonetic,gender,street_address,city
0,IOWA SPECIALTY HOSPITAL- CLARION,India Romeo Lima Mike Zulu Golf Victor Sierra ...,Female,64301 Evergreen Pass,Krajan Jabungcandi
1,SCOTT & WHITE HOSPITAL,Uniform Alfa Lima November Golf Romeo Bravo Vi...,Male,2 Hansons Lane,Além Paraíba
2,SHARKEY ISSAQUENA COMMUNITY HOSPITAL,Sierra Quebec Romeo Kilo Papa Lima Zulu Alfa Y...,Male,74381 Vernon Parkway,Maslovare
3,COLUMBIA ST. MARY'S HOSPITAL MILWAUKEE INC,Juliett Yankee Tango Golf Quebec Bravo Delta U...,Female,23 Lakewood Park,Qumudi
4,"ANGEL MEDICAL CENTER, INC.",Sierra X-ray Romeo Victor Alfa Bravo November ...,Male,31725 Carberry Hill,Tamisan

In [54]:
df.to_csv("mock_hospital_data.csv", index=False)

Saved!